[package]
name = "stellarnova-sc-meta"
version = "0.0.0"
authors = ["StellarNova Team"]
edition = "2021"
publish = false

[dependencies.multiversx-sc-meta-lib]
version = "0.64.0"

[dependencies.stellarnova-sc]
path = ".."

[dev-dependencies]
multiversx-sc-scenario = "0.64.0"
